version: '3'
services:
  spark-master:
    image: spark-master:latest
    ports:
      - '4040:4040'
      - '9090:8080'
      - '7077:7077'
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - 'SPARK_LOCAL_IP=spark-master'
  spark-worker:
    image: spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=512m
      - SPARK_EXECUTOR_MEMORY=512m
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data

  postgres:
    image: postgres:latest
    environment:
      - 'TZ=Europe/Amsterdam'
      - 'POSTGRES_USER=docker'
      - 'POSTGRES_PASSWORD=docker'
    ports:
      - '5432:5432'
    volumes:
      - './sql:/docker-entrypoint-initdb.d'
